# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


ebm_data_config:
  batch_size: 8
  num_workers: 1
  img_shape: (3,256,256)
  hr_images: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
  lr_images: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_LR_mild.zip
  root_path: /Users/vaibhavsingh/Desktop/NYU/DL project/Energy-Based-Models-for-Image-Resolution
  data_path: /Users/vaibhavsingh/Desktop/NYU/DL project/Energy-Based-Models-for-Image-Resolution/Data/ # Change this according to your root.
  saved_model: /Users/vaibhavsingh/Desktop/NYU/DL project/Energy-Based-Models-for-Image-Resolution/Saved Models/EBM ResNet-18/ResNet_EBM.ckpt

ebm_train_config:
  optimiser: Adam
  schedular: StepLR
  learning_rate_exp: 4
  beta1: 0.0
  epochs: 30




